engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  rubocop:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
ratings:
  paths:
  - Gemfile.lock
  - lib/**
  - "**.rb"
exclude_paths:
  - doc/**/*
  - spec/**/*
  - tmp/**/*
